**Importing 10-K**

In [1]:
import edgar

In [2]:
edgar.set_identity("feb2126@columbia.edu")

In [3]:
company = edgar.Company('AAPL')
company

╭───────────────────────────────────────────────────────────────────────────────────╮
│ Apple Inc.  AAPL                                                                  │
│ 0000320193 • Nasdaq • Large Accelerated Filer                                     │
│                                                                                   │
│   Industry          3571: Electronic Computers                                    │
│   Fiscal Year       Sep 26                                                        │
│   Incorporated      California                                                    │
│   Phone             (408) 996-1010                                                │
│   Address           ONE APPLE PARK WAY, CUPERTINO, CA 95014                       │
╰────────────────────────────────── SEC Entity Data • company.docs for usage guide ─╯

In [4]:
filings = company.get_filings(form="10-K")
filings

╭──────────────────────────────────────── Filings for Apple Inc. [320193] ────────────────────────────────────────╮
│                                                                                                                 │
│                                                                              Filing                             │
│    Form        Description                                                   Date         Accession Number      │
│  ─────────────────────────────────────────────────────────────────────────────────────────────────────────────  │
│    10-K        Annual report for public companies                            2025-10-31   0000320193-25-0000…   │
│    10-K        Annual report for public companies                            2024-11-01   0000320193-24-0001…   │
│    10-K        Annual report for public companies                            2023-11-03   0000320193-23-0001…   │
│    10-K        Annual report for public companies                            2022-10-28   0000320193-22-0001…   │
│    10-K        Annual report for public companies                            2021-10-29   0000320193-21-0001…   │
│    10-K        Annual report for public companies                            2020-10-30   0000320193-20-0000…   │
│    10-K        Annual report for public companies                            2019-10-31   0000320193-19-0001…   │
│    10-K        Annual report for public companies                            2018-11-05   0000320193-18-0001…   │
│    10-K        Annual report for public companies                            2017-11-03   0000320193-17-0000…   │
│    10-K        Annual report for public companies                            2016-10-26   0001628280-16-0203…   │
│    10-K        Annual report for public companies                            2015-10-28   0001193125-15-3563…   │
│    10-K        Annual report for public companies                            2014-10-27   0001193125-14-3834…   │
│    10-K        Annual report for public companies                            2013-10-30   0001193125-13-4165…   │
│    10-K        Annual report for public companies                            2012-10-31   0001193125-12-4440…   │
│    10-K        Annual report for public companies                            2011-10-26   0001193125-11-2821…   │
│    10-K        Annual report for public companies                            2010-10-27   0001193125-10-2380…   │
│    10-K/A      Annual report for public companies                            2010-01-25   0001193125-10-0120…   │
│    10-K        Annual report for public companies                            2009-10-27   0001193125-09-2148…   │
│    10-K        Annual report for public companies                            2008-11-05   0001193125-08-2249…   │
│    10-K        Annual report for public companies                            2007-11-15   0001047469-07-0093…   │
│    10-K        Annual report for public companies                            2006-12-29   0001104659-06-0842…   │
│    10-K        Annual report for public companies                            2005-12-01   0001104659-05-0584…   │
│    10-K        Annual report for public companies                            2004-12-03   0001047469-04-0359…   │
│    10-K        Annual report for public companies                            2003-12-19   0001047469-03-0416…   │
│    10-K        Annual report for public companies                            2002-12-19   0001047469-02-0076…   │
│    10-K        Annual report for public companies                            2000-12-14   0000912057-00-0536…   │
│    10-K        Annual report for public companies                            1999-12-22   0000912057-99-0102…   │
│    10-K/A      Annual report for public companies                            1998-01-23   0001047469-98-0018…   │
│    10-K        Annual report for public companies                            1997-12-05   0001047469-97-0069…   │
│    10-K        Annual report for public companies                            1996-12-19   0000320193-96-0000…   │
│    10-K        Annual report for public companies                            1995-12-19   0000320193-95-0000…   │
│    10-K        Annual report for public companies                            1994-12-13   0000320193-94-0000…   │
│                                                                                                                 │
╰─────────────── Company filings between 1994-12-13 and 2025-10-31 • filings.docs for usage guide ────────────────╯

In [5]:
latest_10k = filings.latest()

In [6]:
print([attr for attr in dir(latest_10k) if not attr.startswith('_')])

['acceptance_datetime', 'accession_no', 'accession_number', 'all_ciks', 'all_entities', 'as_company_filing', 'attachments', 'base_dir', 'cik', 'company', 'data_object', 'docs', 'document', 'exhibits', 'file_number', 'filing_date', 'filing_directory', 'filing_url', 'form', 'from_dict', 'from_json', 'from_sgml', 'from_sgml_text', 'full_text_submission', 'get_entity', 'header', 'home', 'homepage', 'homepage_url', 'html', 'index_header_url', 'index_headers', 'is_inline_xbrl', 'is_multi_entity', 'is_xbrl', 'items', 'load', 'markdown', 'obj', 'open', 'open_homepage', 'parsed_items', 'period_of_report', 'primary_doc_description', 'primary_document', 'primary_documents', 'related_filings', 'report_date', 'reports', 'save', 'search', 'sections', 'serve', 'sgml', 'size', 'statements', 'summary', 'text', 'text_url', 'to_context', 'to_dict', 'url', 'view', 'xbrl', 'xml']

In [7]:
all_reports = latest_10k.reports  # type: ignore
all_reports

╭─────────────────────────────────────────── Reports ────────────────────────────────────────────╮
│                                                                                                │
│   #    Report                                                         Category       File      │
│  ────────────────────────────────────────────────────────────────────────────────────────────  │
│   1    Cover Page                                                     Cover          R1.htm    │
│                                                                                                │
│   2    Auditor Information                                            Cover          R2.htm    │
│                                                                                                │
│   3    CONSOLIDATED STATEMENTS OF OPERATIONS                          Statements     R3.htm    │
│                                                                                                │
│   4    CONSOLIDATED STATEMENTS OF COMPREHENSIVE INCOME                Statements     R4.htm    │
│                                                                                                │
│   5    CONSOLIDATED BALANCE SHEETS                                    Statements     R5.htm    │
│                                                                                                │
│   6    CONSOLIDATED BALANCE SHEETS (Parenthetical)                    Statements     R6.htm    │
│                                                                                                │
│   7    CONSOLIDATED STATEMENTS OF SHAREHOLDERS' EQUITY                Statements     R7.htm    │
│                                                                                                │
│   8    CONSOLIDATED STATEMENTS OF CASH FLOWS                          Statements     R8.htm    │
│                                                                                                │
│   9    Summary of Significant Accounting Policies                     Notes          R9.htm    │
│                                                                                                │
│   10   Revenue                                                        Notes          R10.htm   │
│                                                                                                │
│   11   Earnings Per Share                                             Notes          R11.htm   │
│                                                                                                │
│   12   Financial Instruments                                          Notes          R12.htm   │
│                                                                                                │
│   13   Property, Plant and Equipment                                  Notes          R13.htm   │
│                                                                                                │
│   14   Consolidated Financial Statement Details                       Notes          R14.htm   │
│                                                                                                │
│   15   Income Taxes                                                   Notes          R15.htm   │
│                                                                                                │
│   16   Leases                                                         Notes          R16.htm   │
│                                                                                                │
│   17   Debt                                                           Notes          R17.htm   │
│                                                                                                │
│   18   Shareholders' Equity                                           Notes          R18.htm   │
│                                                                                                │
│   19   Share-Based Compensation                                       Notes          R19.htm   │
│                                                                                                │
│   20   Commitments, Contingencies and Supply Concentrations           Notes          R20.htm   │
│                                                                                                │
│   21   Segment Information and Geographic Data                        Notes          R21.htm   │
│                                                                                                │
│   22   Insider Trading Arrangements                                   Notes          R22.htm   │
│                                                                                                │
│   23   Insider Trading Policies and Procedures                        Notes          R23.htm   │
│                                                                                                │
│   24   Cybersecurity Risk Management and Strategy Disclosure          Notes          R24.htm   │
│                                                                                                │
│   25   Summary of Significant Accounting Policies (Policies)          Policies       R25.htm   │
│                                                                                                │
│   26   Revenue (Tables)                                               Tables         R26.htm   │
│                                                                                                │
│   27   Earnings Per Share (Tables)                                    Tables         R27.htm   │
│                                                                                                │
│   28   Financial Instruments (Tables)                                 Tables         R28.htm   │
│                                                                                                │
│   29   Property, Plant and Equipment (Tables)                         Tables         R29.htm   │
│                                                                                                │
│   30   Consolidated Financial Statement Details (Tables)              Tables         R30.htm   │
│                                                                                                │
│   31   Income Taxes (Tables)                                          Tables         R31.htm   │
│                                                                                                │
│   32   Leases (Tables)                                                Tables         R32.htm   │
│                                                                                                │
│   33   Debt (Tables)                                                  Tables         R33.htm   │
│                                                                                                │
│   34   Shareholders' Equity (Tables)                                  Tables         R34.htm   │
│                                                                                                │
│   35   Share-Based Compensation (Tables)                              Tables         R35.htm   │
│                                                                                                │
│   36   Commitments, Contingencies and Supply Concentrations           Tables         R36.htm   │
│        (Tables)                                                                                │
│                                                                                                │
│   37   Segment Information and Geographic Data (Tables)               Tables         R37.htm   │
│                                                                                                │
│   38   Revenue - Disaggregated Net Sales and Portion of Net Sales     Details        R38.htm   │
│        That Was Previously Deferred (Details)                                                  │
│                                                                                                │
│   39   Revenue - Additional Information (Details)                     Details        R39.htm   │
│                                                                                                │
│   40   Revenue - Deferred Revenue, Expected Timing of Realization     Details        R40.htm   │
│        (Details)                                                                               │
│                                                                                                │
│   41   Earnings Per Share - Computation of Basic and Diluted          Details        R41.htm   │
│        Earnings Per Share (Details)                                                            │
│                                                                                                │
│   42   Earnings Per Share - Additional Information (Details)          Details        R42.htm   │
│                                                                                                │
│   43   Financial Instruments - Cash, Cash Equivalents and             Details        R43.htm   │
│        Marketable Securities (Details)                                                         │
│                                                                                                │
│   44   Financial Instruments - Additional Information (Details)       Details        R44.htm   │
│                                                                                                │
│   45   Financial Instruments - Notional Amounts Associated with       Details        R45.htm   │
│        Derivative Instruments (Details)                                                        │
│                                                                                                │
│   46   Property, Plant and Equipment - Gross Property, Plant and      Details        R46.htm   │
│        Equipment by Major Asset Class and Accumulated Depreciation                             │
│        (Details)                                                                               │
│                                                                                                │
│   47   Property, Plant, and Equipment - Additional Information        Details        R47.htm   │
│        (Details)                                                                               │
│                                                                                                │
│   48   Consolidated Financial Statement Details - Other Non-Current   Details        R48.htm   │
│        Assets (Details)                                                                        │
│                                                                                                │
│   49   Consolidated Financial Statement Details - Other Current       Details        R49.htm   │
│        Liabilities (Details)                                                                   │
│                                                                                                │
│   50   Income Taxes - Additional Information (Details)                Details        R50.htm   │
│                                                                                                │
│   51   Income Taxes - Provision for Income Taxes (Details)            Details        R51.htm   │
│                                                                                                │
│   52   Income Taxes - Reconciliation of Provision for Income Taxes    Details        R52.htm   │
│        to Amount Computed by Applying the Statutory Federal Income                             │
│        Tax Rate to Income Before Provision for Income Taxes                                    │
│        (Details)                                                                               │
│                                                                                                │
│   53   Income Taxes - Significant Components of Deferred Tax Assets   Details        R53.htm   │
│        and Liabilities (Details)                                                               │
│                                                                                                │
│   54   Income Taxes - Aggregate Changes in Gross Unrecognized Tax     Details        R54.htm   │
│        Benefits (Details)                                                                      │
│                                                                                                │
│   55   Leases - Additional Information (Details)                      Details        R55.htm   │
│                                                                                                │
│   56   Leases - ROU Assets and Lease Liabilities (Details)            Details        R56.htm   │
│                                                                                                │
│   57   Leases - Lease Liability Maturities (Details)                  Details        R57.htm   │
│                                                                                                │
│   58   Debt - Additional Information (Details)                        Details        R58.htm   │
│                                                                                                │
│   59   Debt - Summary of Cash Flows Associated with Commercial        Details        R59.htm   │
│        Paper (Details)                                                                         │
│                                                                                                │
│   60   Debt - Summary of Term Debt (Details)                          Details        R60.htm   │
│                                                                                                │
│   61   Debt - Future Principal Payments for Term Debt (Details)       Details        R61.htm   │
│                                                                                                │
│   62   Shareholders' Equity - Additional Information (Details)        Details        R62.htm   │
│                                                                                                │
│   63   Shareholders' Equity - Shares of Common Stock (Details)        Details        R63.htm   │
│                                                                                                │
│   64   Share-Based Compensation - Additional Information (Details)    Details        R64.htm   │
│                                                                                                │
│   65   Share-Based Compensation - Restricted Stock Unit Activity      Details        R65.htm   │
│        and Related Information (Details)                                                       │
│                                                                                                │
│   66   Share-Based Compensation - Summary of Share-Based              Details        R66.htm   │
│        Compensation Expense and the Related Income Tax Benefit                                 │
│        (Details)                                                                               │
│                                                                                                │
│   67   Commitments, Contingencies and Supply Concentrations -         Details        R67.htm   │
│        Future Payments Under Unconditional Purchase Obligations                                │
│        (Details)                                                                               │
│                                                                                                │
│   68   Segment Information and Geographic Data - Information by       Details        R68.htm   │
│        Reportable Segment (Details)                                                            │
│                                                                                                │
│   69   Segment Information and Geographic Data - Net Sales for        Details        R69.htm   │
│        Countries that Individually Accounted for More than 10% of                              │
│        the Total (Details)                                                                     │
│                                                                                                │
│   70   Segment Information and Geographic Data - Long-Lived Assets    Details        R70.htm   │
│        for Countries that Individually Accounted for More than 10%                             │
│        of the Total (Details)                                                                  │
│                                                                                                │
│   -    All Reports                                                                             │
│                                                                                                │
╰────────────────────────────────────────────────────────────────────────────────────────────────╯

In [8]:
# Get indices and shortnames from all_reports - STATEMENTS ONLY
reports_df = all_reports.to_pandas()

# Filter to only include statements
statements_df = reports_df[reports_df['MenuCategory'] == 'Statements'].copy()

# Extract index and ShortName for statements only
indices_and_names = statements_df[['ShortName']].reset_index()
print("Statement Indices and ShortNames:")
print(indices_and_names)

# Alternative: Create a dictionary mapping for statements only
index_to_name = dict(zip(statements_df.index, statements_df['ShortName']))
print("\n" + "="*80)
print("\nStatement Index to ShortName mapping:")
for idx, name in index_to_name.items():
    print(f"  {idx}: {name}")

Statement Indices and ShortNames:
   index                                        ShortName
0      2            CONSOLIDATED STATEMENTS OF OPERATIONS
1      3  CONSOLIDATED STATEMENTS OF COMPREHENSIVE INCOME
2      4                      CONSOLIDATED BALANCE SHEETS
3      5      CONSOLIDATED BALANCE SHEETS (Parenthetical)
4      6  CONSOLIDATED STATEMENTS OF SHAREHOLDERS' EQUITY
5      7            CONSOLIDATED STATEMENTS OF CASH FLOWS

================================================================================

Statement Index to ShortName mapping:
  2: CONSOLIDATED STATEMENTS OF OPERATIONS
  3: CONSOLIDATED STATEMENTS OF COMPREHENSIVE INCOME
  4: CONSOLIDATED BALANCE SHEETS
  5: CONSOLIDATED BALANCE SHEETS (Parenthetical)
  6: CONSOLIDATED STATEMENTS OF SHAREHOLDERS' EQUITY
  7: CONSOLIDATED STATEMENTS OF CASH FLOWS

In [9]:
# Build a dictionary to find specific statement types using keywords
import re

# Define keywords for each statement type
statement_keywords = {
    'Income Statement': ['income'],
    'Balance Sheet': ['balance sheet'],
    'Cash Flow Statement': ['cash'],
    'Equity Statement': ['equity'],
}

# Search for statements matching keywords
found_statements = {}

for statement_type, keywords in statement_keywords.items():
    for idx, row in statements_df.iterrows():
        shortname = row['ShortName'].lower()
        
        # Check if any keyword matches
        if any(keyword.lower() in shortname for keyword in keywords):
            if statement_type not in found_statements:
                found_statements[statement_type] = []
            found_statements[statement_type].append({
                'index': idx,
                'shortname': row['ShortName']
            })

# Display results
print("Found Financial Statements:")
print("="*80)
for statement_type, matches in found_statements.items():
    print(f"\n{statement_type}:")
    for match in matches:
        print(f"  Index {match['index']}: {match['shortname']}")

# Create a simplified mapping (taking first match for each type) with shortnames
statement_index_map = {}
statement_name_map = {}
for statement_type, matches in found_statements.items():
    if matches:
        statement_index_map[statement_type] = matches[0]['index']
        statement_name_map[statement_type] = matches[0]['shortname']

print("\n" + "="*80)
print("\nSimplified Statement Index Map (first match only):")
print(statement_index_map)

print("\n" + "="*80)
print("\nSimplified Statement Name Map (first match only):")
for key, value in statement_name_map.items():
    print(f"  {key}: {value}")

Found Financial Statements:
================================================================================

Income Statement:
  Index 3: CONSOLIDATED STATEMENTS OF COMPREHENSIVE INCOME

Balance Sheet:
  Index 4: CONSOLIDATED BALANCE SHEETS
  Index 5: CONSOLIDATED BALANCE SHEETS (Parenthetical)

Cash Flow Statement:
  Index 7: CONSOLIDATED STATEMENTS OF CASH FLOWS

Equity Statement:
  Index 6: CONSOLIDATED STATEMENTS OF SHAREHOLDERS' EQUITY

================================================================================

Simplified Statement Index Map (first match only):
{'Income Statement': 3, 'Balance Sheet': 4, 'Cash Flow Statement': 7, 'Equity Statement': 6}

================================================================================

Simplified Statement Name Map (first match only):
  Income Statement: CONSOLIDATED STATEMENTS OF COMPREHENSIVE INCOME
  Balance Sheet: CONSOLIDATED BALANCE SHEETS
  Cash Flow Statement: CONSOLIDATED STATEMENTS OF CASH FLOWS
  Equity Statement: CONSOLIDATED STATEMENTS OF SHAREHOLDERS' EQUITY

In [10]:
print([attr for attr in dir(all_reports) if not attr.startswith('_')])

['create_from_record', 'current', 'data', 'data_pager', 'filter', 'get_by_category', 'get_by_filename', 'get_by_short_name', 'long_names', 'n', 'next', 'previous', 'short_names', 'statements', 'title', 'to_pandas']

In [11]:
statements = all_reports.statements
print([attr for attr in dir(statements) if not attr.startswith('_')])
detected_statments = statements.detected_statements
print([attr for attr in dir(detected_statments) if not attr.startswith('_')])
print(detected_statments.values())

['balance_sheet', 'cash_flow_statement', 'comprehensive_income_statement', 'detected_statements', 'equity_statement', 'income_statement', 'mapper', 'statements']
['clear', 'copy', 'fromkeys', 'get', 'items', 'keys', 'pop', 'popitem', 'setdefault', 'update', 'values']
dict_values(['CONSOLIDATED STATEMENTS OF OPERATIONS', 'CONSOLIDATED STATEMENTS OF COMPREHENSIVE INCOME', 'CONSOLIDATED BALANCE SHEETS', "CONSOLIDATED STATEMENTS OF SHAREHOLDERS' EQUITY", 'CONSOLIDATED STATEMENTS OF CASH FLOWS'])

In [12]:
report = all_reports.get_by_filename('R50.htm') # type: ignore

In [13]:
print([attr for attr in dir(report) if not attr.startswith('_')])

['content', 'has_embedded_reports', 'html_file_name', 'instance', 'is_default', 'long_name', 'menu_category', 'parent_role', 'position', 'report_type', 'role', 'short_name', 'text', 'to_dataframe', 'view']

In [14]:
report_data = report.content
report_data

'<html>\n<head>\n<title></title>\n<link rel="stylesheet" type="text/css" href="include/report.css">\n<script type="text/javascript" src="Show.js">/* Do Not Remove This Comment */</script><script type="text/javascript">\n\t\t\t\t\t\t\tfunction toggleNextSibling (e) {\n\t\t\t\t\t\t\tif (e.nextSibling.style.display==\'none\') {\n\t\t\t\t\t\t\te.nextSibling.style.display=\'block\';\n\t\t\t\t\t\t\t} else { e.nextSibling.style.display=\'none\'; }\n\t\t\t\t\t\t\t}</script>\n</head>\n<body>\n<span style="display: none;">v3.25.3</span><table class="report" border="0" cellspacing="2" id="id2">\n<tr>\n<th class="tl" colspan="1" rowspan="2"><div style="width: 200px;"><strong>Income Taxes - Additional Information (Details)<br> $ in Millions</strong></div></th>\n<th class="th" colspan="1"></th>\n<th class="th" colspan="1">3 Months Ended</th>\n<th class="th" colspan="3">12 Months Ended</th>\n<th class="th" colspan="1"></th>\n</tr>\n<tr>\n<th class="th">\n<div>Aug. 30, 2016 </div>\n<div>Subsidiary</div>\n</th>\n<th class="th">\n<div>Sep. 28, 2024 </div>\n<div>USD ($)</div>\n</th>\n<th class="th">\n<div>Sep. 27, 2025 </div>\n<div>USD ($)</div>\n</th>\n<th class="th">\n<div>Sep. 28, 2024 </div>\n<div>USD ($)</div>\n</th>\n<th class="th">\n<div>Sep. 30, 2023 </div>\n<div>USD ($)</div>\n</th>\n<th class="th">\n<div>Sep. 24, 2022 </div>\n<div>USD ($)</div>\n</th>\n</tr>\n<tr class="re">\n<td class="pl" style="border-bottom: 0px;" valign="top"><a class="a" href="javascript:void(0);" onclick="Show.showAR( this, \'defref_us-gaap_IncomeTaxContingencyLineItems\', window );"><strong>Income Tax Contingency [Line Items]</strong></a></td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n</tr>\n<tr class="ro">\n<td class="pl" style="border-bottom: 0px;" valign="top"><a class="a" href="javascript:void(0);" onclick="Show.showAR( this, \'defref_us-gaap_CurrentForeignTaxExpenseBenefit\', window );">One-time income tax charge, net, State Aid Decision, portion payable to Ireland</a></td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="nump">$ 8,891<span></span>\n</td>\n<td class="nump">$ 25,483<span></span>\n</td>\n<td class="nump">$ 8,750<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n</tr>\n<tr class="re">\n<td class="pl" style="border-bottom: 0px;" valign="top"><a class="a" href="javascript:void(0);" onclick="Show.showAR( this, \'defref_us-gaap_CurrentFederalTaxExpenseBenefit\', window );">One-time income tax charge, net, State Aid Decision, U.S. foreign tax credit</a></td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="num">(11,487)<span></span>\n</td>\n<td class="num">(5,571)<span></span>\n</td>\n<td class="num">(9,445)<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n</tr>\n<tr class="ro">\n<td class="pl" style="border-bottom: 0px;" valign="top"><a class="a" href="javascript:void(0);" onclick="Show.showAR( this, \'defref_us-gaap_UnrecognizedTaxBenefitsDecreasesResultingFromSettlementsWithTaxingAuthorities\', window );">Decrease in unrecognized tax benefits, State Aid Decision</a></td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="nump">2,939<span></span>\n</td>\n<td class="nump">1,070<span></span>\n</td>\n<td class="nump">19<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n</tr>\n<tr class="re">\n<td class="pl" style="border-bottom: 0px;" valign="top"><a class="a" href="javascript:void(0);" onclick="Show.showAR( this, \'defref_us-gaap_IncomeLossFromContinuingOperationsBeforeIncomeTaxesForeign\', window );">Foreign pre-tax earnings</a></td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="nump">$ 82,000<span></span>\n</td>\n<td class="nump">$ 77,300<span></span>\n</td>\n<td class="nump">$ 72,900<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n</tr>\n<tr class="ro">\n<td class="pl" style="border-bottom: 0px;" valign="top"><a class="a" href="javascript:void(0);" onclick="Show.showAR( this, \'defref_us-gaap_EffectiveIncomeTaxRateReconciliationAtFederalStatutoryIncomeTaxRate\', window );">U.S. statutory federal income tax rate</a></td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="nump">21.00%<span></span>\n</td>\n<td class="nump">21.00%<span></span>\n</td>\n<td class="nump">21.00%<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n</tr>\n<tr class="re">\n<td class="pl" style="border-bottom: 0px;" valign="top"><a class="a" href="javascript:void(0);" onclick="Show.showAR( this, \'defref_us-gaap_DeferredTaxAssetsTaxCreditCarryforwardsForeign\', window );">Foreign tax credit carryforwards</a></td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="nump">$ 4,700<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n</tr>\n<tr class="ro">\n<td class="pl" style="border-bottom: 0px;" valign="top"><a class="a" href="javascript:void(0);" onclick="Show.showAR( this, \'defref_us-gaap_DeferredTaxAssetsTaxCreditCarryforwardsResearch\', window );">Research and development tax credit carryforwards</a></td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="nump">4,000<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n</tr>\n<tr class="re">\n<td class="pl" style="border-bottom: 0px;" valign="top"><a class="a" href="javascript:void(0);" onclick="Show.showAR( this, \'defref_us-gaap_UnrecognizedTaxBenefits\', window );">Gross unrecognized tax benefits</a></td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="nump">$ 22,038<span></span>\n</td>\n<td class="nump">23,242<span></span>\n</td>\n<td class="nump">$ 22,038<span></span>\n</td>\n<td class="nump">$ 19,454<span></span>\n</td>\n<td class="nump">$ 16,758<span></span>\n</td>\n</tr>\n<tr class="ro">\n<td class="pl" style="border-bottom: 0px;" valign="top"><a class="a" href="javascript:void(0);" onclick="Show.showAR( this, \'defref_us-gaap_UnrecognizedTaxBenefitsThatWouldImpactEffectiveTaxRate\', window );">Gross unrecognized tax benefits that would impact effective tax rate, if recognized</a></td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="nump">10,800<span></span>\n</td>\n<td class="nump">10,600<span></span>\n</td>\n<td class="nump">$ 10,800<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n</tr>\n<tr class="re">\n<td class="pl" style="border-bottom: 0px;" valign="top"><a class="a" href="javascript:void(0);" onclick="Show.showAR( this, \'defref_us-gaap_DecreaseInUnrecognizedTaxBenefitsIsReasonablyPossible\', window );">Reasonably possible decrease in gross unrecognized tax benefits over next 12 months</a></td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="nump">$ 6,000<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n</tr>\n<tr class="rh">\n<td class="pl" style="border-bottom: 0px;" valign="top"><a class="a" href="javascript:void(0);" onclick="Show.showAR( this, \'defref_us-gaap_LossContingenciesByNatureOfContingencyAxis=aapl_UnfavorableInvestigationOutcomeEUStateAidRulesMember\', window );">Unfavorable investigation outcome, EU State Aid rules</a></td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n</tr>\n<tr class="re">\n<td class="pl" style="border-bottom: 0px;" valign="top"><a class="a" href="javascript:void(0);" onclick="Show.showAR( this, \'defref_us-gaap_IncomeTaxContingencyLineItems\', window );"><strong>Income Tax Contingency [Line Items]</strong></a></td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n</tr>\n<tr class="ro">\n<td class="pl custom" style="border-bottom: 0px;" valign="top"><a class="a" href="javascript:void(0);" onclick="Show.showAR( this, \'defref_aapl_IncomeTaxContingencyNumberOfSubsidiaries\', window );">Number of subsidiaries impacted by the European Commission tax ruling | Subsidiary</a></td>\n<td class="nump">2<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n</tr>\n<tr class="re">\n<td class="pl" style="border-bottom: 0px;" valign="top"><a class="a" href="javascript:void(0);" onclick="Show.showAR( this, \'defref_us-gaap_CurrentIncomeTaxExpenseBenefit\', window );">One-time income tax charge, net, State Aid Decision</a></td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="nump">10,200<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n</tr>\n<tr class="ro">\n<td class="pl" style="border-bottom: 0px;" valign="top"><a class="a" href="javascript:void(0);" onclick="Show.showAR( this, \'defref_us-gaap_CurrentForeignTaxExpenseBenefit\', window );">One-time income tax charge, net, State Aid Decision, portion payable to Ireland</a></td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="nump">15,800<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n</tr>\n<tr class="re">\n<td class="pl" style="border-bottom: 0px;" valign="top"><a class="a" href="javascript:void(0);" onclick="Show.showAR( this, \'defref_us-gaap_CurrentFederalTaxExpenseBenefit\', window );">One-time income tax charge, net, State Aid Decision, U.S. foreign tax credit</a></td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="nump">4,800<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n</tr>\n<tr class="ro">\n<td class="pl" style="border-bottom: 0px;" valign="top"><a class="a" href="javascript:void(0);" onclick="Show.showAR( this, \'defref_us-gaap_UnrecognizedTaxBenefitsDecreasesResultingFromSettlementsWithTaxingAuthorities\', window );">Decrease in unrecognized tax benefits, State Aid Decision</a></td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="nump">$ 823<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n<td class="text">&#160;<span></span>\n</td>\n</tr>\n</table>\n<div style="display: none;">\n<table border="0" cellpadding="0" cellspacing="0" class="authRefData" style="display: none;" id="defref_aapl_IncomeTaxContingencyNumberOfSubsidiaries">\n<tr><td class="hide"><a style="color: white;" href="javascript:void(0);" onclick="Show.hideAR();">X</a></td></tr>\n<tr><td><div class="body" style="padding: 2px;">\n<a href="javascript:void(0);" onclick="Show.toggleNext( this );">- Definition</a><div><p>Number of subsidiaries involved in investigation.</p></div>\n<a href="javascript:void(0);" onclick="Show.toggleNext( this );">+ References</a><div style="display: none;"><p>No definition available.</p></div>\n<a href="javascript:void(0);" onclick="Show.toggleNext( this );">+ Details</a><div style="display: none;"><table border="0" cellpadding="0" cellspacing="0">\n<tr>\n<td><strong> Name:</strong></td>\n<td style="white-space:nowrap;">aapl_IncomeTaxContingencyNumberOfSubsidiaries</td>\n</tr>\n<tr>\n<td style="padding-right: 4px;white-space:nowrap;"><strong> Namespace Prefix:</strong></td>\n<td>aapl_</td>\n</tr>\n<tr>\n<td><strong> Data Type:</strong></td>\n<td>xbrli:integerItemType</td>\n</tr>\n<tr>\n<td><strong> Balance Type:</strong></td>\n<td>na</td>\n</tr>\n<tr>\n<td><strong> Period Type:</strong></td>\n<td>duration</td>\n</tr>\n</table></div>\n</div></td></tr>\n</table>\n<table border="0" cellpadding="0" cellspacing="0" class="authRefData" style="display: none;" id="defref_us-gaap_CurrentFederalTaxExpenseBenefit">\n<tr><td class="hide"><a style="color: white;" href="javascript:void(0);" onclick="Show.hideAR();">X</a></td></tr>\n<tr><td><div class="body" style="padding: 2px;">\n<a href="javascript:void(0);" onclick="Show.toggleNext( this );">- Definition</a><div><p>Amount of current federal tax expense (benefit) attributable to income (loss) from continuing operations. Includes, but is not limited to, current national tax expense (benefit) for non-US (United States of America) jurisdiction.</p></div>\n<a href="javascript:void(0);" onclick="Show.toggleNext( this );">+ References</a><div style="display: none;"><p>Reference 1: http://www.xbrl.org/2009/role/commonPracticeRef<br> -Topic 235<br> -SubTopic 10<br> -Name Accounting Standards Codification<br> -Section S50<br> -Paragraph 1<br> -Publisher FASB<br> -URI https://asc.fasb.org/1943274/2147480738/235-10-S50-1<br><br>Reference 2: http://www.xbrl.org/2009/role/commonPracticeRef<br> -Topic 740<br> -SubTopic 10<br> -Name Accounting Standards Codification<br> -Section S99<br> -Paragraph 1<br> -Subparagraph (SAB Topic 6.I.7)<br> -Publisher FASB<br> -URI https://asc.fasb.org/1943274/2147479360/740-10-S99-1<br><br>Reference 3: http://www.xbrl.org/2009/role/commonPracticeRef<br> -Topic 235<br> -SubTopic 10<br> -Name Accounting Standards Codification<br> -Section S99<br> -Paragraph 1<br> -Subparagraph (SX 210.4-08(h)(1)(Note 1))<br> -Publisher FASB<br> -URI https://asc.fasb.org/1943274/2147480678/235-10-S99-1<br><br>Reference 4: http://www.xbrl.org/2009/role/commonPracticeRef<br> -Name Accounting Standards Codification<br> -Section 50<br> -Paragraph 9<br> -Subparagraph (a)<br> -SubTopic 10<br> -Topic 740<br> -Publisher FASB<br> -URI https://asc.fasb.org/1943274/2147482685/740-10-50-9<br></p></div>\n<a href="javascript:void(0);" onclick="Show.toggleNext( this );">+ Details</a><div style="display: none;"><table border="0" cellpadding="0" cellspacing="0">\n<tr>\n<td><strong> Name:</strong></td>\n<td style="white-space:nowrap;">us-gaap_CurrentFederalTaxExpenseBenefit</td>\n</tr>\n<tr>\n<td style="padding-right: 4px;white-space:nowrap;"><strong> Namespace Prefix:</strong></td>\n<td>us-gaap_</td>\n</tr>\n<tr>\n<td><strong> Data Type:</strong></td>\n<td>xbrli:monetaryItemType</td>\n</tr>\n<tr>\n<td><strong> Balance Type:</strong></td>\n<td>debit</td>\n</tr>\n<tr>\n<td><strong> Period Type:</strong></td>\n<td>duration</td>\n</tr>\n</table></div>\n</div></td></tr>\n</table>\n<table border="0" cellpadding="0" cellspacing="0" class="authRefData" style="display: none;" id="defref_us-gaap_CurrentForeignTaxExpenseBenefit">\n<tr><td class="hide"><a style="color: white;" href="javascript:void(0);" onclick="Show.hideAR();">X</a></td></tr>\n<tr><td><div class="body" style="padding: 2px;">\n<a href="javascript:void(0);" onclick="Show.toggleNext( this );">- Definition</a><div><p>Amount of current foreign income tax expense (benefit) pertaining to income (loss) from continuing operations.</p></div>\n<a href="javascript:void(0);" onclick="Show.toggleNext( this );">+ References</a><div style="display: none;"><p>Reference 1: http://www.xbrl.org/2009/role/commonPracticeRef<br> -Topic 235<br> -SubTopic 10<br> -Name Accounting Standards Codification<br> -Section S50<br> -Paragraph 1<br> -Publisher FASB<br> -URI https://asc.fasb.org/1943274/2147480738/235-10-S50-1<br><br>Reference 2: http://www.xbrl.org/2009/role/commonPracticeRef<br> -Topic 235<br> -SubTopic 10<br> -Name Accounting Standards Codification<br> -Section S99<br> -Paragraph 1<br> -Subparagraph (SX 210.4-08(h)(1)(Note 1))<br> -Publisher FASB<br> -URI https://asc.fasb.org/1943274/2147480678/235-10-S99-1<br><br>Reference 3: http://www.xbrl.org/2009/role/commonPracticeRef<br> -Name Accounting Standards Codification<br> -Section 50<br> -Paragraph 9<br> -Subparagraph (a)<br> -SubTopic 10<br> -Topic 740<br> -Publisher FASB<br> -URI https://asc.fasb.org/1943274/2147482685/740-10-50-9<br></p></div>\n<a href="javascript:void(0);" onclick="Show.toggleNext( this );">+ Details</a><div style="display: none;"><table border="0" cellpadding="0" cellspacing="0">\n<tr>\n<td><strong> Name:</strong></td>\n<td style="white-space:nowrap;">us-gaap_CurrentForeignTaxExpenseBenefit</td>\n</tr>\n<tr>\n<td style="padding-right: 4px;white-space:nowrap;"><strong> Namespace Prefix:</strong></td>\n<td>us-gaap_</td>\n</tr>\n<tr>\n<td><strong> Data Type:</strong></td>\n<td>xbrli:monetaryItemType</td>\n</tr>\n<tr>\n<td><strong> Balance Type:</strong></td>\n<td>debit</td>\n</tr>\n<tr>\n<td><strong> Period Type:</strong></td>\n<td>duration</td>\n</tr>\n</table></div>\n</div></td></tr>\n</table>\n<table border="0" cellpadding="0" cellspacing="0" class="authRefData" style="display: none;" id="defref_us-gaap_CurrentIncomeTaxExpenseBenefit">\n<tr><td class="hide"><a style="color: white;" href="javascript:void(0);" onclick="Show.hideAR();">X</a></td></tr>\n<tr><td><div class="body" style="padding: 2px;">\n<a href="javascript:void(0);" onclick="Show.toggleNext( this );">- Definition</a><div><p>Amount of current income tax expense (benefit) pertaining to taxable income (loss) from continuing operations.</p></div>\n<a href="javascript:void(0);" onclick="Show.toggleNext( this );">+ References</a><div style="display: none;"><p>Reference 1: http://www.xbrl.org/2009/role/commonPracticeRef<br> -Topic 235<br> -SubTopic 10<br> -Name Accounting Standards Codification<br> -Section S50<br> -Paragraph 1<br> -Publisher FASB<br> -URI https://asc.fasb.org/1943274/2147480738/235-10-S50-1<br><br>Reference 2: http://www.xbrl.org/2009/role/commonPracticeRef<br> -Topic 235<br> -SubTopic 10<br> -Name Accounting Standards Codification<br> -Section S99<br> -Paragraph 1<br> -Subparagraph (SX 210.4-08(h)(1)(Note 1))<br> -Publisher FASB<br> -URI https://asc.fasb.org/1943274/2147480678/235-10-S99-1<br><br>Reference 3: http://www.xbrl.org/2003/role/disclosureRef<br> -Topic 740<br> -SubTopic 10<br> -Name Accounting Standards Codification<br> -Section 50<br> -Paragraph 9<br> -Subparagraph (a)<br> -Publisher FASB<br> -URI https://asc.fasb.org/1943274/2147482685/740-10-50-9<br></p></div>\n<a href="javascript:void(0);" onclick="Show.toggleNext( this );">+ Details</a><div style="display: none;"><table border="0" cellpadding="0" cellspacing="0">\n<tr>\n<td><strong> Name:</strong></td>\n<td style="white-space:nowrap;">us-gaap_CurrentIncomeTaxExpenseBenefit</td>\n</tr>\n<tr>\n<td style="padding-right: 4px;white-space:nowrap;"><strong> Namespace Prefix:</strong></td>\n<td>us-gaap_</td>\n</tr>\n<tr>\n<td><strong> Data Type:</strong></td>\n<td>xbrli:monetaryItemType</td>\n</tr>\n<tr>\n<td><strong> Balance Type:</strong></td>\n<td>debit</td>\n</tr>\n<tr>\n<td><strong> Period Type:</strong></td>\n<td>duration</td>\n</tr>\n</table></div>\n</div></td></tr>\n</table>\n<table border="0" cellpadding="0" cellspacing="0" class="authRefData" style="display: none;" id="defref_us-gaap_DecreaseInUnrecognizedTaxBenefitsIsReason

In [15]:
tenk = latest_10k.obj()
tenk

╭──────────────────────────────────────────────── Apple Inc. 10-K ────────────────────────────────────────────────╮
│ Period ending September 27, 2025 filed on October 31, 2025                                                      │
│                                                                                                                 │
│                                                                                                                 │
│ 📄                                                                                                              │
│ ├── PART I                                                                                                      │
│ │   ├── Item 1  Business                                                                                        │
│ │   ├── Item 1A Risk Factors                                                                                    │
│ │   ├── Item 1B Unresolved Staff Comments                                                                       │
│ │   ├── Item 1C Cybersecurity                                                                                   │
│ │   ├── Item 2  Properties                                                                                      │
│ │   ├── Item 3  Legal Proceedings                                                                               │
│ │   └── Item 4  Mine Safety Disclosures                                                                         │
│ ├── PART II                                                                                                     │
│ │   ├── Item 5  Market for Registrant's Common Equity                                                           │
│ │   ├── Item 6  Selected Financial Data                                                                         │
│ │   ├── Item 7  Management's Discussion and Analysis (MD&A)                                                     │
│ │   ├── Item 7A Quantitative and Qualitative Disclosures About Market Risk                                      │
│ │   ├── Item 8  Financial Statements                                                                            │
│ │   ├── Item 9  Controls and Procedures                                                                         │
│ │   ├── Item 9A Controls and Procedures                                                                         │
│ │   ├── Item 9B Other Information                                                                               │
│ │   └── Item 9C Disclosure Regarding Foreign Jurisdictions That Prevent Inspections                             │
│ ├── PART III                                                                                                    │
│ │   ├── Item 10 Directors, Executive Officers, and Corporate Governance                                         │
│ │   ├── Item 11 Executive Compensation                                                                          │
│ │   ├── Item 12 Security Ownership of Certain Beneficial Owners and Management                                  │
│ │   ├── Item 13 Certain Relationships and Related Transactions, and Director Independence                       │
│ │   └── ITEM 14: Principal Accounting Fees and Services                                                         │
│ └── PART IV                                                                                                     │
│     ├── Item 15 Exhibits, Financial Statement Schedules                                                         │
│     └── Item 16 Form 10-K Summary                                                                               │
│                                                                                                                 │
│                                                                                                                 │
│ ╭─────────────────────────────────────────────── XBRL Document ───────────────────────────────────────────────╮ │
│ │ Apple Inc. (AAPL) • CIK 0000320193                                                                          │ │
│ │                                                                                                             │ │
│ │          Form:  10-K                                                                                        │ │
│ │ Fiscal Period:  Fiscal Year 2025 (ended Sep 27, 2025)                                                       │ │
│ │          Data:  1,131 facts • 182 contexts                                                                  │ │
│ │                                                                                                             │ │
│ │ Periods Available for Statements:                                                                           │ │
│ │   Annual: FY 2025, FY 2024, FY 2023                                                                         │ │
│ │   Quarterly: June 29, 2025 to September 27, 2025, June 30, 2024 to September 28, 2024                       │ │
│ │   (1 future period after 2025-09-27 excluded)                                                               │ │
│ │                                                                                                             │ │
│ │ Common Actions                                                                                              │ │
│ │ ────────────────────────────────────────────────────────────                                                │ │
│ │ # List all available statements                                                                             │ │
│ │   xbrl.statements                                                                                           │ │
│ │                                                                                                             │ │
│ │ # Access statements by name or index                                                                        │ │
│ │   stmt = xbrl.statements['CoverPage']                                                                       │ │
│ │   stmt = xbrl.statements[6]                                                                                 │ │
│ │                                                                                                             │ │
│ │ # View core financial statements                                                                            │ │
│ │   stmt = xbrl.statements.income_statement()                                                                 │ │
│ │   stmt = xbrl.statements.balance_sheet()                                                                    │ │
│ │   stmt = xbrl.statements.cash_flow_statement()                                                              │ │
│ │   stmt = xbrl.statements.statement_of_equity()                                                              │ │
│ │   stmt = xbrl.statements.comprehensive_income()                                                             │ │
│ │                                                                                                             │ │
│ │ # Get current period only                                                                                   │ │
│ │   current = xbrl.current_period                                                                             │ │
│ │   stmt = current.income_statement()                                                                         │ │
│ │                                                                                                             │ │
│ │ # Convert statement to DataFrame                                                                            │ │
│ │   df = stmt.to_dataframe()                                                                                  │ │
│ │                                                                                                             │ │
│ │ # Query specific facts                                                                                      │ │
│ │   revenue = xbrl.facts.query().by_concept('Revenue').to_dataframe()                                         │ │
│ │                                                                                                             │ │
│ │ 💡 Tip: Use xbrl.docs for comprehensive usage guide                                                         │ │
│ ╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────╯ │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

In [16]:
print([attr for attr in dir(tenk) if not attr.startswith('_')])

['balance_sheet', 'business', 'cash_flow_statement', 'chunked_document', 'company', 'directors_officers_and_governance', 'doc', 'document', 'filing_date', 'financials', 'form', 'get_item_with_part', 'get_structure', 'id_parse_document', 'income_statement', 'items', 'management_discussion', 'period_of_report', 'risk_factors', 'sections', 'structure', 'view']

In [17]:
business = tenk.business
business

'Item 1.\xa0\xa0\xa0\xa0Business\n\nCompany Background\n\nThe Company designs, manufactures and markets smartphones, personal computers, tablets, wearables and accessories, and sells a variety of related services. The Company’s fiscal year is the 52- or 53-week period that ends on the last Saturday of September.\n\nProducts\n\niPhone\n\niPhone® is the Company’s line of smartphones based on its iOS operating system. The iPhone line includes iPhone 17 Pro, iPhone Air™, iPhone 17, iPhone 16 and iPhone 16e.\n\nMac\n\nMac® is the Company’s line of personal computers based on its macOS® operating system. The Mac line includes laptops MacBook Air® and MacBook Pro®, as well as desktops iMac®, Mac mini®, Mac Studio® and Mac Pro®.\n\niPad\n\niPad® is the Company’s line of multipurpose tablets based on its iPadOS® operating system. The iPad line includes iPad Pro®, iPad Air®, iPad and iPad mini®.\n\nWearables, Home and Accessories\n\nWearables includes smartwatches, wireless headphones and spatial computers. The Company’s line of smartwatches, based on its watchOS® operating system, includes Apple Watch® Series 11, Apple Watch SE® 3 and Apple Watch Ultra® 3. The Company’s line of wireless headphones includes AirPods®, AirPods Pro®, AirPods Max® and Beats® products. Apple Vision Pro™ is the Company’s spatial computer based on its visionOS® operating system.\n\nHome includes Apple TV 4K®, the Company’s media streaming and gaming device based on its tvOS® operating system, and HomePod® and HomePod mini®, high-fidelity wireless smart speakers.\n\nAccessories includes Apple-branded and third-party accessories.\n\nApple Inc. | 2025 Form 10-K | 1\n\nServices\n\nAdvertising\n\nThe Company’s advertising services include third-party licensing arrangements and the Company’s own advertising platforms.\n\nAppleCare\n\nThe Company offers a portfolio of fee-based service and support products under the AppleCare® brand. The offerings provide priority access to Apple technical support, access to the global Apple authorized service network for repair and replacement services, and in many cases additional coverage for instances of accidental damage or theft and loss, depending on the country and type of product.\n\nCloud Services\n\nThe Company’s cloud services store and keep customers’ content up-to-date and available across multiple Apple devices and Windows personal computers.\n\nDigital Content\n\nThe Company operates various platforms, including the App Store®, that allow customers to discover and download applications and digital content, such as books, music, video, games and podcasts.\n\nThe Company also offers digital content through subscription-based services, including Apple Arcade®, a game service; Apple Fitness+®, a personalized fitness service; Apple Music®, which offers users a curated listening experience with on-demand radio stations; Apple News+®, a news and magazine service; and Apple TV®, which offers exclusive original content and live sports.\n\nPayment Services\n\nThe Company offers payment services, including Apple Card®, a co-branded credit card, and Apple Pay®, a cashless payment service.\n\nSegments\n\nThe Company manages its business primarily on a geographic basis. The Company’s reportable segments consist of the Americas, Europe, Greater China, Japan and Rest of Asia Pacific. Americas includes both North and South America. Europe includes European countries, as well as India, the Middle East and Africa. Greater China includes China mainland, Hong Kong and Taiwan. Rest of Asia Pacific includes Australia, New Zealand and those Asian countries not included in the Company’s other reportable segments. Although the reportable segments provide similar hardware and software products and similar services, each one is managed separately to better align with the location of the Company’s customers and distribution partners and the unique market dynamics of each geographic region.\n\nMarkets and Distribution\n\nThe Company’s customers are primarily in the consumer, small and mid-sized business, education, enterprise and government markets. The Company sells its products and resells third-party products in most of its major markets directly to customers through its retail and online stores and its direct sales force. The Company sells its services in the same markets through its various service platforms. The Company also employs a variety of indirect distribution channels, such as third-party cellular network carriers and other resellers, for the sale of its products and certain of its services. During 2025, the Company’s net sales through its direct and indirect distribution channels accounted for 40% and 60%, respectively, of total net sales.\n\nCompetition\n\nThe markets for the Company’s products and services are highly competitive and are characterized by aggressive price competition, downward pressure on gross margins, continual improvement in product performance, and price sensitivity on the part of consumers and businesses. The markets in which the Company competes are further defined by frequent introduction of new products and services, short product life cycles, evolving industry standards, and rapid adoption of technological advancements by competitors. Many of the Company’s competitors seek to compete primarily through aggressive pricing and very low cost structures, and by imitating the Company’s products and infringing on its intellectual property.\n\nApple Inc. | 2025 Form 10-K | 2\n\nThe Company’s ability to compete successfully depends heavily on ensuring the continuing and timely introduction of innovative new products, services and technologies to the marketplace. The Company designs and develops nearly the entire solution for its products, including the hardware, operating system, numerous software applications and related services. Principal competitive factors important to the Company include price, product and service features (including security features), relative price and performance, product and service quality and reliability, design and technology innovation, a strong third-party software and accessories ecosystem, marketing and distribution capability, service and support, corporate reputation, and the ability to effectively protect and enforce the Company’s intellectual property rights.\n\nThe Company is focused on expanding its market opportunities related to smartphones, personal computers, tablets, wearables and accessories, and services. The Company’s products and services face substantial competition from companies that have significant technical, marketing, distribution and other resources, as well as established hardware, software, and service offerings with large customer bases. In addition, the Company faces significant competition as competitors imitate the Company’s product features and applications within their products to offer more competitive solutions. The Company also expects competition to intensify as competitors imitate the Company’s approach to providing components seamlessly within their offerings or work collaboratively to offer integrated solutions. Some of the Company’s competitors have broad product lines, low-priced products, large installed bases of active devices, and large customer bases. Competition has been particularly intense as competitors have aggressively cut prices and lowered product margins. Certain competitors have the resources, experience or cost structures to provide products and services at little or no profit or even at a loss. The Company has a minority market share in the global smartphone, personal computer, tablet and wearables markets, and some of the markets in which the Company competes have from time to time experienced little to no growth or contracted overall.\n\nSupply of Components\n\nAlthough most components essential to the Company’s business are generally available from multiple sources, certain components are currently obtained from single or limited sources. The Company also competes for various components with other participants in the markets for smartphones, personal computers, tablets, wearables and accessories. Therefore, many components used by the Company, including those that are available from multiple sources, are at times subject to industry-wide shortage and significant commodity pricing fluctuations. Restrictions on international trade can increase the cost or limit the availability of the Company’s products and the components and rare earths and other raw materials that go into them.\n\nThe Company uses some custom components that are not commonly used by its competitors, and new products introduced by the Company often utilize custom components available from only one source. When a component or product uses new technologies, initial capacity constraints may exist until the suppliers’ yields have matured or their manufacturing capacities have increased. The Company has entered into agreements for the supply of many components; however, the Company may not be able to extend or renew agreements for the supply of components on similar terms, or at all, and may not be successful in obtaining sufficient quantities from its suppliers or in a timely manner, or in identifying and obtaining sufficient quantities from an alternative source. In addition, component suppliers may fail, be subject to consolidation within a particular industry, or decide to concentrate on the production of common components instead of components customized to meet the Company’s requirements, further limiting the Company’s ability to obtain sufficient quantities of components on commercially reasonable terms, or at all.\n\nResearch and Development\n\nBecause the industries in which the Company competes are characterized by rapid technological advances, the Company’s ability to compete successfully depends heavily upon its ability to ensure a continual and timely flow of competitive products, services and technologies to the marketplace. The Company continues to develop new technologies to enhance existing products and services, and to expand the range of its offerings through research and development (“R&D”), licensing of intellectual property and acquisition of third-party businesses and technology.\n\nIntellectual Property\n\nThe Company currently holds a broad collection of intellectual property rights relating to certain aspects of its hardware, software and services. This includes patents, designs, copyrights, trademarks, trade secrets and other forms of intellectual property rights in the U.S. and various foreign countries. Although the Company believes the ownership of such intellectual property rights is an important factor in differentiating its business and that its success does depend in part on such ownership, the Company relies primarily on the innovative skills, technical competence and marketing abilities of its personnel.\n\nThe Company regularly files patent, design, copyright and trademark applications to protect innovations arising from its hardware, software and service research, development, design and marketing, and is currently pursuing thousands of applications around the world. Over time, the Company has accumulated a large portfolio of issued and registered intellectual property rights around the world. No single intellectual property right is solely responsible for protecting the Company’s products and services. The Company believes the duration of its intellectual property rights is adequate relative to the expected lives of its products and services.\n\nApple Inc. | 2025 Form 10-K | 3\n\nIn addition to Company-owned intellectual property, many of the Company’s products and services include technology or intellectual property that must be licensed from third parties. It may be necessary in the future to seek or renew licenses relating to various aspects of the Company’s products, processes and services. While the Company has generally been able to obtain such licenses on commercially reasonable terms in the past, there is no guarantee that such licenses could be obtained in the future on reasonable terms or at all.\n\nBusiness Seasonality and Product Introductions\n\nThe Company has historically experienced higher net sales in its first quarter compared to other quarters in its fiscal year due in part to seasonal holiday demand. Additionally, new product and service introductions can significantly impact net sales, cost of sales and operating expenses. The timing of product introductions can also impact the Company’s net sales to its indirect distribution channels as these channels are filled with new inventory following a product launch, and channel inventory of an older product often declines as the launch of a newer product approaches. Net sales can also be affected when consumers and distributors anticipate a product introduction.\n\nHuman Capital\n\nThe Company believes that its people play an important role in its success, and strives to attract, develop and retain the best talent. The Company works to create a culture of collaboration, one where people with a broad range of backgrounds and perspectives can come together to innovate and do the best work of their lives. The Company is an equal opportunity employer committed to inclusion and to providing a workplace free of harassment or discrimination. As of September\xa027, 2025, the Company had approximately 166,000 full-time equivalent employees.\n\nThe Company believes that compensation should be competitive and equitable, and offers discretionary cash and equity awards to enable employees to share in the Company’s success. The Company recognizes its people are most likely to thrive when they have the resources to meet their needs and the time and support to succeed in their professional and personal lives. In support of this, the Company offers a wide variety of benefits for employees around the world, including health, wellness and time away.\n\nThe Company invests in resources to help its people develop and achieve their career goals. The Company offers programs through Apple University on leadership, management and influence, as well as Apple culture and values. Team members can also take advantage of online classes for business, technical and personal development.\n\nThe Company believes that open and honest communication among team members, managers and leaders helps create an open, collaborative work environment where everyone can contribute, grow and succeed. Team members are encouraged to come to their managers with questions, feedback or concerns, and the Company conducts surveys that gauge employee sentiment in areas like career development, manager performance and inclusion.\n\nThe Company is committed to the safety and security of its team members everywhere it operates. The Company supports employees with general safety, security and crisis management training, and by putting specific programs in place for those working in potentially high-hazard environments.\n\nAvailable Information\n\nThe Company’s Annual Reports on Form 10-K, Quarterly Reports on Form 10-Q, Current Reports on Form 8-K, and amendments to reports filed pursuant to Sections 13(a) and 15(d) of the Securities Exchange Act of 1934, as amended (“Exchange Act”), are filed with the U.S. Securities and Exchange Commission (“SEC”). Such reports and other information filed by the Company with the SEC are available free of charge at investor.apple.com/investor-relations/sec-filings/default.aspx when such reports are available on the SEC’s website. The Company periodically provides certain information for investors on its corporate website, www.apple.com, and its investor relations website, investor.apple.com. This includes press releases and other information about financial performance, information on corporate governance, and details related to the Company’s annual meeting of shareholders. The information contained on the websites referenced in this Form 10-K is not incorporated by reference into this filing. Further, the Company’s references to website URLs are intended to be inactive textual references only.\n\nApple Inc. | 2025 Form 10-K | 4'

**Try to make a Function that Pulls all the PARTS and Items**

In [18]:
tenk_obj = tenk.structure.structure
tenk_obj

{'PART I': {'ITEM 1': {'Title': 'Business',
   'Description': "Overview of the company's business operations, products, services, and market environment."},
  'ITEM 1A': {'Title': 'Risk Factors',
   'Description': "Discussion of risks and uncertainties that could materially affect the company's financial condition or results of operations."},
  'ITEM 1B': {'Title': 'Unresolved Staff Comments',
   'Description': "Any comments from the SEC staff on the company's previous filingsthat remain unresolved."},
  'ITEM 1C': {'Title': 'Cybersecurity',
   'Description': 'Cybersecurity risk management, strategy, and governance disclosures.'},
  'ITEM 2': {'Title': 'Properties',
   'Description': 'Information about the physical properties owned or leased by the company.'},
  'ITEM 3': {'Title': 'Legal Proceedings',
   'Description': 'Details of significant ongoing legal proceedings.'},
  'ITEM 4': {'Title': 'Mine Safety Disclosures',
   'Description': 'Relevant for mining companies, disclosures about mine safety and regulatory compliance.'}},
 'PART II': {'ITEM 5': {'Title': "Market for Registrant's Common Equity",
   'Description': "Information on the company's equity, including stock performance and shareholder matters."},
  'ITEM 6': {'Title': 'Selected Financial Data',
   'Description': 'Financial data summary for the last five fiscal years.'},
  'ITEM 7': {'Title': "Management's Discussion and Analysis (MD&A)",
   'Description': "Management's perspective on the financial condition, changes in financial condition, and results of operations."},
  'ITEM 7A': {'Title': 'Quantitative and Qualitative Disclosures About Market Risk',
   'Description': "Information on the company's exposure to market risk, such as interest rate risk, foreign currency exchange risk, commodity price risk, etc."},
  'ITEM 8': {'Title': 'Financial Statements',
   'Description': 'Complete audited financial statements, including balance sheet, income statement, cash flow statement, and notes to the financial statements.'},
  'ITEM 9': {'Title': 'Controls and Procedures',
   'Description': "Evaluation of the effectiveness of the design and operation of the company's disclosure controls and procedures."},
  'ITEM 9A': {'Title': 'Controls and Procedures',
   'Description': 'Evaluation of internal controls over financial reporting.'},
  'ITEM 9B': {'Title': 'Other Information',
   'Description': 'Any other relevant information not covered in other sections.'},
  'ITEM 9C': {'Title': 'Disclosure Regarding Foreign Jurisdictions That Prevent Inspections',
   'Description': 'Disclosure Regarding Foreign Jurisdictions That Prevent Inspections.'}},
 'PART III': {'ITEM 10': {'Title': 'Directors, Executive Officers, and Corporate Governance',
   'Description': "Information about the company's directors, executive officers, and governance policies."},
  'ITEM 11': {'Title': 'Executive Compensation',
   'Description': 'Details of compensation paid to key executives.'},
  'ITEM 12': {'Title': 'Security Ownership of Certain Beneficial Owners and Management',
   'Description': 'Information about stock ownership of major shareholders, directors, and management.'},
  'ITEM 13': {'Title': 'Certain Relationships and Related Transactions, and Director Independence',
   'Description': 'Information on transactions between the company and its directors, officers, and significant shareholders.'},
  'ITEM 14': {'Title': 'Principal Accounting Fees and Services',
   'Description': 'Fees paid to the principal accountant and services rendered.'}},
 'PART IV': {'ITEM 15': {'Title': 'Exhibits, Financial Statement Schedules',
   'Description': 'Legal documents and financial schedules that support the financial statements and disclosures.'},
  'ITEM 16': {'Title': 'Form 10-K Summary',
   'Description': 'Form 10-K Summary'}}}

In [19]:
print([attr for attr in dir(tenk_obj) if not attr.startswith('_')])

['clear', 'copy', 'fromkeys', 'get', 'items', 'keys', 'pop', 'popitem', 'setdefault', 'update', 'values']

In [20]:
item_by_part = tenk.get_item_with_part(part='PART I', item='Item 1A')

In [21]:
def format_text_with_newlines(text_obj):
    """
    Format text output to properly display newlines.
    
    Args:
        text_obj: Text string or object that returns text
    
    Returns:
        None (prints formatted text)
    """
    # Get text string if it's a method/object
    if callable(text_obj):
        text = text_obj()
    else:
        text = str(text_obj)
    
    # Print the text (print() automatically renders \n as newlines)
    print(text)

In [22]:
formatted_text = format_text_with_newlines(item_by_part)

Item 1A.    Risk Factors

The following summarizes factors that could have a material adverse effect on the Company’s business, reputation, results of operations, financial condition and stock price. The Company may not be able to accurately predict, control or mitigate these risks. Statements in this section are based on the Company’s beliefs and opinions regarding matters that could materially adversely affect the Company in the future and are not representations as to whether such matters have or have not occurred previously. The risks and uncertainties described below are not exhaustive and should not be considered a complete statement of all potential risks or uncertainties that the Company faces or may face in the future.

This section should be read in conjunction with Part II, Item 7, “Management’s Discussion and Analysis of Financial Condition and Results of Operations” and the consolidated financial statements and accompanying notes in Part II, Item 8, “Financial Statements and Supplementary Data” of this Form 10-K.

Macroeconomic and Industry Risks

The Company’s operations and performance depend significantly on global and regional economic conditions and adverse economic conditions can materially adversely affect the Company’s business, results of operations, financial condition and stock price.

The Company has international operations with sales outside the U.S. representing a majority of the Company’s total net sales. In addition, the Company’s global supply chain is large and complex and a majority of the Company’s supplier facilities, including manufacturing and assembly sites, are located outside the U.S. As a result, the Company’s operations and performance depend significantly on global and regional economic conditions.

Adverse macroeconomic conditions, including slow growth or recession, high unemployment, inflation, tighter credit, higher interest rates, and currency fluctuations, can adversely impact consumer confidence and spending and materially adversely affect demand for the Company’s products and services. In addition, consumer confidence and spending can be materially adversely affected in response to changes in fiscal and monetary policy, financial market volatility, declines in income or asset values, and other economic factors.

Uncertainty about, or a decline in, global or regional economic conditions can also have a significant impact on the Company’s suppliers, contract manufacturers, logistics providers, distributors, cellular network carriers and other channel partners, and developers. Potential outcomes include financial instability; inability to obtain credit to finance business operations; and insolvency.

Adverse economic conditions can also lead to increased credit and collectibility risk on the Company’s trade receivables; the failure of derivative counterparties and other financial institutions; limitations on the Company’s ability to issue new debt; reduced liquidity; and declines in the fair values of the Company’s financial instruments. These and other impacts can materially adversely affect the Company’s business, results of operations, financial condition and stock price.

Apple Inc. | 2025 Form 10-K | 5

The Company’s business can be impacted by political events, trade and other international disputes, geopolitical tensions, conflict, terrorism, natural disasters, public health issues, industrial accidents and other business interruptions.

Political events, trade and other international disputes, geopolitical tensions, conflict, terrorism, natural disasters, public health issues, industrial accidents and other business interruptions can have a material adverse effect on the Company and its customers, employees, suppliers, contract manufacturers, logistics providers, distributors, cellular network carriers and other channel partners.

The Company has a large, global business with sales outside the U.S. representing a majority of the Company’s total net sales, and the Company believes that it generally benefits from growth in international trade. A significant majority of the Company’s manufacturing is performed in whole or in part by outsourcing partners located primarily in China mainland, India, Japan, South Korea, Taiwan and Vietnam, in addition to sourcing from partners and facilities located in the U.S. Restrictions on international trade, such as tariffs and other controls on imports or exports of goods, technology or data, can materially adversely affect the Company’s business and supply chain. The impact can be particularly significant if these restrictive measures apply to countries and regions where the Company derives a significant portion of its revenues and/or has significant supply chain operations. Restrictive measures can increase the cost or limit the availability of the Company’s products and the components and rare earths and other raw materials that go into them. Restrictive measures can also require the Company to change suppliers, restructure business relationships and operations, refrain from offering and distributing or cease to offer and distribute affected products, services and third-party applications to its customers, and increase the prices of its products and services. Changing the Company’s business and supply chain in accordance with new or changed restrictions on international trade can be expensive, time-consuming and disruptive to the Company’s business and results of operations. Trade and other international disputes can also have an adverse impact on the overall macroeconomic environment and result in shifts and reductions in consumer spending and negative consumer sentiment for the Company’s products and services, all of which can further adversely affect the Company’s business and results of operations. Such restrictions can be announced with little or no advance notice, which can create uncertainty, and the Company may not be able to effectively mitigate any or all adverse impacts from such measures. Global supply chains can be highly concentrated, and an escalation of geopolitical tensions or conflict could result in significant disruptions. Beginning in the second quarter of 2025, new tariffs were announced on imports to the U.S. (“U.S. Tariffs”), including additional tariffs on imports from China, India, Japan, South Korea, Taiwan, Vietnam and the European Union (“EU”), among others. In response, several countries have imposed, or threatened to impose, reciprocal tariffs on imports from the U.S. and other retaliatory measures. Various modifications to the U.S. Tariffs have been announced and further changes could be made in the future, which may include additional sector-based tariffs or other measures. For example, the U.S. Department of Commerce has initiated an investigation under Section 232 of the Trade Expansion Act of 1962, as amended, into, among other things, imports of semiconductors, semiconductor manufacturing equipment, and their derivative products, including downstream products that contain semiconductors. The ultimate impact remains uncertain and will depend on several factors, including whether additional or incremental U.S. Tariffs or other measures are announced or imposed, to what extent other countries implement tariffs or other retaliatory measures in response, and the overall magnitude and duration of these measures. If disputes and conflicts further escalate, actions by governments in response could be significantly more severe and restrictive.

Many of the Company’s operations, retail stores and facilities, as well as critical business operations of the Company’s suppliers and contract manufacturers, are in locations that are prone to earthquakes and other natural disasters. Global climate change is resulting in certain types of natural disasters and extreme weather occurring more frequently or with more intense effects. In addition, the Company’s and its suppliers’ operations, retail stores and facilities are subject to the risk of interruption by fire, power shortages, nuclear power plant accidents and other industrial accidents, terrorist attacks and other hostile acts, ransomware and other cybersecurity attacks, labor disputes, public health issues and other events beyond the Company’s control.

Such events can make it difficult or impossible for the Company to manufacture and deliver products to its customers, create delays and inefficiencies in the Company’s supply and manufacturing chain, result in slowdowns and outages to the Company’s service offerings, increase the Company’s costs, and negatively impact consumer spending and demand in affected areas.

The Company’s operations are also subject to the risks of industrial accidents at its suppliers and contract manufacturers. While the Company’s suppliers are required to maintain safe working environments and operations, an industrial accident could occur and could result in serious injuries or loss of life, disruption to the Company’s business, and harm to the Company’s reputation. Major public health issues, including pandemics such as the COVID-19 pandemic, have adversely affected, and could in the future materially adversely affect, the Company due to their impact on the global economy and demand for consumer products; the imposition of protective public safety measures, such as stringent employee travel restrictions and limitations on freight services and the movement of products between regions; and disruptions in the Company’s operations, supply chain and sales and distribution channels, resulting in interruptions to the supply of current products and offering of existing services, and delays in production ramps of new products and development of new services.

Apple Inc. | 2025 Form 10-K | 6

Following any interruption to its business, the Company can require substantial recovery time, incur significant expenditures to resume operations, and lose significant sales. Because the Company relies on single or limited sources for the supply and manufacture of many critical components, a business interruption affecting such sources would exacerbate any negative consequences to the Company. While the Company maintains insurance coverage for certain types of losses, such insurance coverage may be insufficient to cover all losses that may arise. Any of the foregoing can materially adversely affect the Company’s business, results of operations, financial condition and stock price.

Global markets for the Company’s products and services are highly competitive and subject to rapid technological change, and the Company may be unable to compete effectively in these markets.

The Company’s products and services are offered in highly competitive global markets. These markets are characterized by aggressive price competition, downward pressure on gross margins, continual improvement in product performance, and price sensitivity on the part of consumers and businesses. These markets are further defined by frequent introduction of new products and services, short product life cycles, evolving industry standards, and rapid adoption of technological advancements.

The Company’s ability to compete successfully depends heavily on ensuring the continuing and timely introduction of innovative new products, services and technologies to the marketplace. The Company designs and develops nearly the entire solution for its products, including the hardware, operating system, numerous software applications and related services. As a result, the Company must make significant investments in R&D. These investments may not achieve expected returns, and the Company may not be able to develop and market new products and services successfully.

The Company’s ability to compete successfully also depends on the effective protection and enforcement of its intellectual property rights. Regulatory requirements, government investigations and litigation can force the Company to withdraw from, or modify its products and services for, certain countries and limit its ability to derive value from, or to enjoin others from using, its intellectual property rights. Additionally, they may require the Company to share its innovations with competitors. Any of these outcomes can have a negative impact on the Company’s competitive advantage and materially adversely affect its business, results of operations, financial condition and stock price.

The Company currently holds a significant number of patents, trademarks and copyrights and has registered, and applied to register, additional patents, trademarks and copyrights. In contrast, many of the Company’s competitors seek to compete primarily through aggressive pricing and very low cost structures, and by imitating the Company’s products and infringing on its intellectual property. Effective intellectual property protection is not consistently available in every country in which the Company operates. If the Company is unable to continue to develop and sell innovative new products with attractive margins or if competitors infringe on the Company’s intellectual property, the Company’s ability to maintain a competitive advantage could be materially adversely affected.

The Company’s products and services face substantial competition from companies that have significant technical, marketing, distribution and other resources, as well as established hardware, software and service offerings. In addition, the Company faces significant competition as competitors imitate the Company’s product features and applications within their products to offer more competitive solutions. The Company also expects competition to intensify as competitors imitate the Company’s approach to providing components seamlessly within their offerings or work collaboratively to offer integrated solutions. Some of the Company’s competitors have broad product lines, low-priced products, large installed bases of active devices, and large customer bases. Competition has been particularly intense as competitors have aggressively cut prices and lowered product margins. Certain competitors have the resources, experience or cost structures to provide products and services at little or no profit or even at a loss. The Company has a minority market share in the global smartphone, personal computer, tablet and wearables markets, and some of the markets in which the Company competes have from time to time experienced little to no growth or contracted overall.

If the Company is unable to compete successfully, its business, reputation, results of operations, financial condition and stock price can be materially adversely affected.

Apple Inc. | 2025 Form 10-K | 7

Business Risks

To remain competitive and stimulate customer demand, the Company must successfully manage frequent introductions and transitions of products and services.

Due to the highly volatile and competitive nature of the markets and industries in which the Company competes, the Company must continually introduce new products, services and technologies, enhance existing products and services, effectively stimulate customer demand for new and upgraded products and services, navigate global regulatory requirements and barriers to market access, and successfully manage the transition to these new and upgraded products and services. The success of new product and service introductions depends on a number of factors, including the Company’s ability to recruit and retain highly skilled personnel to execute on its strategic initiatives, and the timely and successful development and market acceptance of new products, services and technologies. Success also relies on the Company’s ability to manage the risks associated with new technologies and production ramp-up issues, the effective integration of third-party services and technologies into the Company’s products and services, the availability, delivery and performance of application software or other third-party support for the Company’s products and services, the effective management of manufacturing and other purchase commitments and the management of inventory levels in line with anticipated product demand, and the availability of products in appropriate quantities and at expected costs to meet anticipated demand. Additionally, quality issues or other defects or deficiencies can adversely affect the success of new product and service introductions and market acceptance. New products, services and technologies may replace or supersede existing offerings and may produce lower revenues and lower profit margins. The Company may not be able to successfully manage future introductions and transitions of products and services, which can materially adversely affect the Company’s business, reputation, results of operations, financial condition and stock price.

The Company depends on component and product manufacturing and logistical services provided by outsourcing partners, many of which are located outside of the U.S.

A significant majority of the Company’s manufacturing is performed in whole or in part by outsourcing partners located primarily in China mainland, India, Japan, South Korea, Taiwan and Vietnam, in addition to sourcing from partners and facilities located in the U.S. The Company relies on single-source partners in the U.S., Asia and Europe to supply and manufacture many components, and on partners primarily located in Asia, for final assembly of substantially all of the Company’s hardware products. The Company has also outsourced much of its transportation and logistics management. While these arrangements can lower operating costs, they also reduce the Company’s direct control over production and distribution. Such diminished control has from time to time had, and may in the future have, an adverse effect on the cost, quality or quantity of products manufactured or services provided, or adversely affect the Company’s flexibility to respond to changing conditions. Although arrangements with these partners may contain provisions for product defect expense reimbursement, the Company generally remains responsible to the consumer for warranty and out-of-warranty service in the event of product defects and experiences unanticipated product defect liabilities from time to time. While the Company relies on its partners to adhere to its supplier code of conduct, violations of the supplier code of conduct occur from time to time and can materially adversely affect the Company’s business, reputation, results of operations, financial condition and stock price.

Changes or additions to the Company’s supply chain require considerable time and resources and involve significant risks and uncertainties, including exposure to additional regulatory and operational risks.

Future operating results depend upon the Company’s ability to obtain components in sufficient quantities on commercially reasonable terms.

Because the Company currently obtains certain components from single or limited sources, the Company is subject to significant supply and pricing risks. Many components, including those that are available from multiple sources, are at times subject to industry-wide shortages and significant commodity pricing fluctuations that can materially adversely affect the Company’s business, results of operations, financial condition and stock price. For example, the global semiconductor industry has in the past experienced high demand and shortages of supply, which adversely affected the Company’s ability to obtain sufficient quantities of components and products on commercially reasonable terms, or at all. Such disruptions could occur in the future.


In [23]:
def extract_parts_and_items(tenk_obj):
    """
    Extract PARTs and Items from a 10-K XBRL object.
    
    Args:
        tenk_obj: The 10-K object returned from filing.obj()
    
    Returns:
        dict: Dictionary with structure {PART: [Items]} and 'all_items' key for flat list
    """
    result = {}
    
    # Access the pre-built structure directly
    structure_dict = tenk_obj.structure.structure
    
    # Parse the structure dictionary
    for part, items_dict in structure_dict.items():
        result[part] = list(items_dict.keys())
        
    return result

In [24]:
tenk_dict = extract_parts_and_items(tenk)
tenk_dict

{'PART I': ['ITEM 1',
  'ITEM 1A',
  'ITEM 1B',
  'ITEM 1C',
  'ITEM 2',
  'ITEM 3',
  'ITEM 4'],
 'PART II': ['ITEM 5',
  'ITEM 6',
  'ITEM 7',
  'ITEM 7A',
  'ITEM 8',
  'ITEM 9',
  'ITEM 9A',
  'ITEM 9B',
  'ITEM 9C'],
 'PART III': ['ITEM 10', 'ITEM 11', 'ITEM 12', 'ITEM 13', 'ITEM 14'],
 'PART IV': ['ITEM 15', 'ITEM 16']}

**Function to Extract Report Data**

This function retrieves report data by filename and automatically converts statements/tables to DataFrames.

In [25]:
import pandas as pd

def get_report_data(reports_obj, filename, return_dataframe=True):
    """
    Extract data from a specific report file in a 10-K filing.
    
    Args:
        reports_obj: The reports object from filing.reports
        filename: The filename of the report (e.g., 'R3.htm', 'R5.htm')
        return_dataframe: If True and the report is a statement/table, returns DataFrame
                         If False or report is not tabular, returns the report object
    
    Returns:
        pd.DataFrame or Report object: DataFrame for statements/tables, Report object otherwise
    """
    # Get the report by filename
    report = reports_obj.get_by_filename(filename)
    
    if report is None:
        raise ValueError(f"Report with filename '{filename}' not found")
    
    # Print report info
    print(f"Report: {report.long_name}")
    print(f"Category: {report.menu_category}")
    print(f"Filename: {report.html_file_name}")
    print("-" * 80)
    
    # Check if it's a statement or table that can be converted to DataFrame
    statement_categories = 'Statements'
    
    if return_dataframe and report.menu_category in statement_categories:
        try:
            df = report.to_dataframe()
            print(f"\n✓ Converted to DataFrame: {df.shape[0]} rows × {df.shape[1]} columns\n")
            return df
        except Exception as e:
            print(f"\n✗ Could not convert to DataFrame: {e}")
            print("Returning report object instead\n")
            return report
    else:
        # For non-tabular reports (Cover, etc.), return the report object
        print(f"\nReport type '{report.menu_category}' - returning report object")
        print("Use .content or .text to access the data\n")
        return report

# Example usage
print("Available reports:")
reports_list = all_reports.to_pandas()
print(reports_list[['ShortName', 'MenuCategory', 'HtmlFileName']].head(10))

Available reports:
                                         ShortName MenuCategory HtmlFileName
0                                       Cover Page        Cover       R1.htm
1                              Auditor Information        Cover       R2.htm
2            CONSOLIDATED STATEMENTS OF OPERATIONS   Statements       R3.htm
3  CONSOLIDATED STATEMENTS OF COMPREHENSIVE INCOME   Statements       R4.htm
4                      CONSOLIDATED BALANCE SHEETS   Statements       R5.htm
5      CONSOLIDATED BALANCE SHEETS (Parenthetical)   Statements       R6.htm
6  CONSOLIDATED STATEMENTS OF SHAREHOLDERS' EQUITY   Statements       R7.htm
7            CONSOLIDATED STATEMENTS OF CASH FLOWS   Statements       R8.htm
8       Summary of Significant Accounting Policies        Notes       R9.htm
9                                          Revenue        Notes      R10.htm

In [26]:
# Test 1: Get Income Statement as DataFrame
income_statement = get_report_data(all_reports, 'R3.htm')
income_statement.head()

Report: 9952151 - Statement - CONSOLIDATED STATEMENTS OF OPERATIONS
Category: Statements
Filename: R3.htm
--------------------------------------------------------------------------------

✓ Converted to DataFrame: 0 rows × 0 columns

Empty DataFrame
Columns: []
Index: []

In [27]:
print([attr for attr in dir(income_statement) if not attr.startswith('_')])

['T', 'abs', 'add', 'add_prefix', 'add_suffix', 'agg', 'aggregate', 'align', 'all', 'any', 'apply', 'applymap', 'asfreq', 'asof', 'assign', 'astype', 'at', 'at_time', 'attrs', 'axes', 'backfill', 'between_time', 'bfill', 'bool', 'boxplot', 'clip', 'columns', 'combine', 'combine_first', 'compare', 'convert_dtypes', 'copy', 'corr', 'corrwith', 'count', 'cov', 'cummax', 'cummin', 'cumprod', 'cumsum', 'describe', 'diff', 'div', 'divide', 'dot', 'drop', 'drop_duplicates', 'droplevel', 'dropna', 'dtypes', 'duplicated', 'empty', 'eq', 'equals', 'eval', 'ewm', 'expanding', 'explode', 'ffill', 'fillna', 'filter', 'first', 'first_valid_index', 'flags', 'floordiv', 'from_dict', 'from_records', 'ge', 'get', 'groupby', 'gt', 'head', 'hist', 'iat', 'idxmax', 'idxmin', 'iloc', 'index', 'infer_objects', 'info', 'insert', 'interpolate', 'isetitem', 'isin', 'isna', 'isnull', 'items', 'iterrows', 'itertuples', 'join', 'keys', 'kurt', 'kurtosis', 'last', 'last_valid_index', 'le', 'loc', 'lt', 'map', 'mask', 'max', 'mean', 'median', 'melt', 'memory_usage', 'merge', 'min', 'mod', 'mode', 'mul', 'multiply', 'ndim', 'ne', 'nlargest', 'notna', 'notnull', 'nsmallest', 'nunique', 'pad', 'pct_change', 'pipe', 'pivot', 'pivot_table', 'plot', 'pop', 'pow', 'prod', 'product', 'quantile', 'query', 'radd', 'rank', 'rdiv', 'reindex', 'reindex_like', 'rename', 'rename_axis', 'reorder_levels', 'replace', 'resample', 'reset_index', 'rfloordiv', 'rmod', 'rmul', 'rolling', 'round', 'rpow', 'rsub', 'rtruediv', 'sample', 'select_dtypes', 'sem', 'set_axis', 'set_flags', 'set_index', 'shape', 'shift', 'size', 'skew', 'sort_index', 'sort_values', 'sparse', 'squeeze', 'stack', 'std', 'style', 'sub', 'subtract', 'sum', 'swapaxes', 'swaplevel', 'tail', 'take', 'to_clipboard', 'to_csv', 'to_dict', 'to_excel', 'to_feather', 'to_gbq', 'to_hdf', 'to_html', 'to_json', 'to_latex', 'to_markdown', 'to_numpy', 'to_orc', 'to_parquet', 'to_period', 'to_pickle', 'to_records', 'to_sql', 'to_stata', 'to_string', 'to_timestamp', 'to_xarray', 'to_xml', 'transform', 'transpose', 'truediv', 'truncate', 'tz_convert', 'tz_localize', 'unstack', 'update', 'value_counts', 'values', 'var', 'where', 'xs']

In [28]:
# Test 2: Get Balance Sheet as DataFrame
balance_sheet = get_report_data(all_reports, 'R5.htm')
balance_sheet

Report: 9952153 - Statement - CONSOLIDATED BALANCE SHEETS
Category: Statements
Filename: R5.htm
--------------------------------------------------------------------------------

✓ Converted to DataFrame: 0 rows × 0 columns

Empty DataFrame
Columns: []
Index: []

In [29]:
# Test 3: Get Notes report - it will be converted to DataFrame by default
notes_report = get_report_data(all_reports, 'R50.htm')

print("\n✓ Result is a Report object")
# Access the text property (not a method)
print("\n" + "="*80)
print("REPORT TEXT DATA:")
print("="*80)
print(notes_report.text())  # Access text as a property, not a method

Report: 9955536 - Disclosure - Income Taxes - Additional Information (Details)
Category: Details
Filename: R50.htm
--------------------------------------------------------------------------------

Report type 'Details' - returning report object
Use .content or .text to access the data


✓ Result is a Report object

================================================================================
REPORT TEXT DATA:
================================================================================

 Income Taxes - Additional
 Information (Details)
 $ in Millions                                        3 Months
 Income Taxes - Additional                               Ended     12 Months
 Information (Details)                   Aug. 30,     Sep. 28,         Ended     Sep. 28,    Sep. 30,     Sep. 24,
 $ in Millions                               2016         2024 Sep. 27, 2025         2024        2023         2022
 Income Tax Contingency [Line Items]   Subsidiary      USD ($)       USD ($)      USD ($)     USD ($)      USD ($)
 ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 One-time income tax charge, net,
 State Aid Decision, portion payable                                 $ 8,891     $ 25,483     $ 8,750
 to Ireland
 One-time income tax charge, net,
 State Aid Decision, U. S. foreign                                  (11,487)      (5,571)     (9,445)
 tax credit
 Decrease in unrecognized tax                                          2,939        1,070          19
 benefits, State Aid Decision
 Foreign pre-tax earnings                                           $ 82,000     $ 77,300    $ 72,900
 U. S. statutory federal income tax                                      21%          21%         21%
 rate
 Foreign tax credit carryforwards                                    $ 4,700
 Research and development tax credit                                   4,000
 carryforwards
 Gross unrecognized tax benefits                      $ 22,038        23,242     $ 22,038    $ 19,454     $ 16,758
 Gross unrecognized tax benefits that
 would impact effective tax rate, if                    10,800        10,600     $ 10,800
 recognized
 Reasonably possible decrease in
 gross unrecognized tax benefits over                                $ 6,000
 next 12 months
 Unfavorable investigation outcome,
 EU State Aid rules
 Income Tax Contingency [Line Items]
 Number of subsidiaries impacted by
 the European Commission tax ruling |           2
 Subsidiary
 One-time income tax charge, net,                       10,200
 State Aid Decision
 One-time income tax charge, net,
 State Aid Decision, portion payable                    15,800
 to Ireland
 One-time income tax charge, net,
 State Aid Decision, U. S. foreign                       4,800
 tax credit
 Decrease in unrecognized tax                            $ 823
 benefits, State Aid Decision

**Write a Funtion to give me a list of string with the file names**

In [30]:
reports_df = all_reports.to_pandas()
reports_df

,instance,IsDefault,HasEmbeddedReports,HtmlFileName,LongName,ReportType,Role,ParentRole,ShortName,MenuCategory,Position
0,aapl-20250927.htm,False,False,R1.htm,0000001 - Document - Cover Page,Sheet,http://www.apple.com/role/CoverPage,None,Cover Page,Cover,1
1,aapl-20250927.htm,False,False,R2.htm,0000002 - Document - Auditor Information,Sheet,http://www.apple.com/role/AuditorInformation,None,Auditor Information,Cover,2
2,aapl-20250927.htm,False,False,R3.htm,9952151 - Statement - CONSOLIDATED STATEMENTS ...,Sheet,http://www.apple.com/role/CONSOLIDATEDSTATEMEN...,None,CONSOLIDATED STATEMENTS OF OPERATIONS,Statements,3
3,aapl-20250927.htm,False,False,R4.htm,9952152 - Statement - CONSOLIDATED STATEMENTS ...,Sheet,http://www.apple.com/role/CONSOLIDATEDSTATEMEN...,None,CONSOLIDATED STATEMENTS OF COMPREHENSIVE INCOME,Statements,4
4,aapl-20250927.htm,False,False,R5.htm,9952153 - Statement - CONSOLIDATED BALANCE SHEETS,Sheet,http://www.apple.com/role/CONSOLIDATEDBALANCES...,None,CONSOLIDATED BALANCE SHEETS,Statements,5
...,...,...,...,...,...,...,...,...,...,...,...
66,aapl-20250927.htm,False,False,R67.htm,"9955553 - Disclosure - Commitments, Contingenc...",Sheet,http://www.apple.com/role/CommitmentsContingen...,None,"Commitments, Contingencies and Supply Concentr...",Details,67
67,aapl-20250927.htm,False,False,R68.htm,9955554 - Disclosure - Segment Information and...,Sheet,http://www.apple.com/role/SegmentInformationan...,None,Segment Information and Geographic Data - Info...,Details,68
68,aapl-20250927.htm,False,False,R69.htm,9955555 - Disclosure - Segment Information and...,Sheet,http://www.apple.com/role/SegmentInformationan...,None,Segment Information and Geographic Data - Net ...,Details,69
69,aapl-20250927.htm,False,False,R70.htm,9955556 - Disclosure - Segment Information and...,Sheet,http://www.apple.com/role/SegmentInformationan...,None,Segment Information and Geographic Data - Long...,Details,70
70,None,False,False,None,All Reports,Book,None,None,All Reports,None,None

In [31]:
def get_report_filenames(reports_obj):
    """
    Extract all report filenames from a reports object.
    
    Args:
        reports_obj: The reports object from filing.reports
    
    Returns:
        list: List of filename strings (e.g., ['R1.htm', 'R2.htm', ...])
    """
    # Convert reports to DataFrame and extract HtmlFileName column
    reports_df = reports_obj.to_pandas()
    filenames = reports_df['HtmlFileName'].dropna().tolist()  # Drop None values
    
    return filenames

In [32]:
filenames = get_report_filenames(all_reports)
print(f"Found {len(filenames)} report files:\n")
print(filenames)

Found 70 report files:

['R1.htm', 'R2.htm', 'R3.htm', 'R4.htm', 'R5.htm', 'R6.htm', 'R7.htm', 'R8.htm', 'R9.htm', 'R10.htm', 'R11.htm', 'R12.htm', 'R13.htm', 'R14.htm', 'R15.htm', 'R16.htm', 'R17.htm', 'R18.htm', 'R19.htm', 'R20.htm', 'R21.htm', 'R22.htm', 'R23.htm', 'R24.htm', 'R25.htm', 'R26.htm', 'R27.htm', 'R28.htm', 'R29.htm', 'R30.htm', 'R31.htm', 'R32.htm', 'R33.htm', 'R34.htm', 'R35.htm', 'R36.htm', 'R37.htm', 'R38.htm', 'R39.htm', 'R40.htm', 'R41.htm', 'R42.htm', 'R43.htm', 'R44.htm', 'R45.htm', 'R46.htm', 'R47.htm', 'R48.htm', 'R49.htm', 'R50.htm', 'R51.htm', 'R52.htm', 'R53.htm', 'R54.htm', 'R55.htm', 'R56.htm', 'R57.htm', 'R58.htm', 'R59.htm', 'R60.htm', 'R61.htm', 'R62.htm', 'R63.htm', 'R64.htm', 'R65.htm', 'R66.htm', 'R67.htm', 'R68.htm', 'R69.htm', 'R70.htm']

**Pulling the statment files Directly**

In [33]:
xb = latest_10k.xbrl()
xb

╭───────────────────────────────────────────────── XBRL Document ─────────────────────────────────────────────────╮
│ Apple Inc. (AAPL) • CIK 0000320193                                                                              │
│                                                                                                                 │
│          Form:  10-K                                                                                            │
│ Fiscal Period:  Fiscal Year 2025 (ended Sep 27, 2025)                                                           │
│          Data:  1,131 facts • 182 contexts                                                                      │
│                                                                                                                 │
│ Periods Available for Statements:                                                                               │
│   Annual: FY 2025, FY 2024, FY 2023                                                                             │
│   Quarterly: June 29, 2025 to September 27, 2025, June 30, 2024 to September 28, 2024                           │
│   (1 future period after 2025-09-27 excluded)                                                                   │
│                                                                                                                 │
│ Common Actions                                                                                                  │
│ ────────────────────────────────────────────────────────────                                                    │
│ # List all available statements                                                                                 │
│   xbrl.statements                                                                                               │
│                                                                                                                 │
│ # Access statements by name or index                                                                            │
│   stmt = xbrl.statements['CoverPage']                                                                           │
│   stmt = xbrl.statements[6]                                                                                     │
│                                                                                                                 │
│ # View core financial statements                                                                                │
│   stmt = xbrl.statements.income_statement()                                                                     │
│   stmt = xbrl.statements.balance_sheet()                                                                        │
│   stmt = xbrl.statements.cash_flow_statement()                                                                  │
│   stmt = xbrl.statements.statement_of_equity()                                                                  │
│   stmt = xbrl.statements.comprehensive_income()                                                                 │
│                                                                                                                 │
│ # Get current period only                                                                                       │
│   current = xbrl.current_period                                                                                 │
│   stmt = current.income_statement()                                                                             │
│                                                                                                                 │
│ # Convert statement to DataFrame                                                                                │
│   df = stmt.to_dataframe()                                                                                      │
│                                                                                                                 │
│ # Query specific facts                                                                                          │
│   revenue = xbrl.facts.query().by_concept('Revenue').to_dataframe()                                             │
│                                                                                                                 │
│ 💡 Tip: Use xbrl.docs for comprehensive usage guide                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

In [34]:
statements = xb.statements
statements

Financial Statements

  #     Name                                           Type                  Parenthetical
 ───────────────────────────────────────────────────────────────────────────────────────────
  4     CONSOLIDATEDBALANCESHEETS                      BalanceSheet
  7     CONSOLIDATEDSTATEMENTSOFCASHFLOWS              CashFlowStatement
  3     CONSOLIDATEDSTATEMENTSOFCOMPREHENSIVEINCOME    ComprehensiveIncome
  2     CONSOLIDATEDSTATEMENTSOFOPERATIONS             IncomeStatement
  6     CONSOLIDATEDSTATEMENTSOFSHAREHOLDERSEQUITY     StatementOfEquity
  59    ShareholdersEquitySharesofCommonStockDetails   StatementOfEquity

Notes to Financial Statements

  #     Name                                             Type                 Parenthetical
 ────────────────────────────────────────────────────────────────────────────────────────────
  8     SummaryofSignificantAccountingPolicies           AccountingPolicies
  21    SummaryofSignificantAccountingPoliciesPolicies   AccountingPolicies

Disclosures

  #     Name                                                                   Type                Parenthetical
 ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  67    AwardTimingDisclosure                                                  Disclosures
  68    ErrCompDisclosure                                                      Disclosures
  69    PvpDisclosure                                                          Disclosures
  20    SegmentInformationandGeographicData                                    SegmentDisclosure
  64    SegmentInformationandGeographicDataInformationbyReportableSegmentDe…   SegmentDisclosure
  66    SegmentInformationandGeographicDataLongLivedAssetsforCountriesthatI…   SegmentDisclosure
  65    SegmentInformationandGeographicDataNetSalesforCountriesthatIndividu…   SegmentDisclosure
  33    SegmentInformationandGeographicDataTables                              SegmentDisclosure

Document Sections

  #     Name        Type        Parenthetical
 ──────────────────────────────────────────────
  0     CoverPage   CoverPage

Other Sections

  #     Name                                                           Type                        Parenthetical
 ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  1     AuditorInformation
  19    CommitmentsContingenciesandSupplyConcentrations
  63    CommitmentsContingenciesandSupplyConcentrationsFuturePaymen…
  32    CommitmentsContingenciesandSupplyConcentrationsTables
  13    ConsolidatedFinancialStatementDetails
  45    ConsolidatedFinancialStatementDetailsOtherCurrentLiabilitie…
  44    ConsolidatedFinancialStatementDetailsOtherNonCurrentAssetsD…
  26    ConsolidatedFinancialStatementDetailsTables
  16    Debt
  54    DebtAdditionalInformationDetails
  57    DebtFuturePrincipalPaymentsforTermDebtDetails
  55    DebtSummaryofCashFlowsAssociatedwithCommercialPaperDetails
  56    DebtSummaryofTermDebtDetails
  29    DebtTables
  10    EarningsPerShare
  38    EarningsPerShareAdditionalInformationDetails
  37    EarningsPerShareComputationofBasicandDilutedEarningsPerShar…
  23    EarningsPerShareTables
  11    FinancialInstruments
  40    FinancialInstrumentsAdditionalInformationDetails
  39    FinancialInstrumentsCashCashEquivalentsandMarketableSecurit…
  41    FinancialInstrumentsNotionalAmountsAssociatedwithDerivative…
  24    FinancialInstrumentsTables
  14    IncomeTaxes
  46    IncomeTaxesAdditionalInformationDetails
  50    IncomeTaxesAggregateChangesinGrossUnrecognizedTaxBenefitsDe…
  47    IncomeTaxesProvisionforIncomeTaxesDetails
  48    IncomeTaxesReconciliationofProvisionforIncomeTaxestoAmountC…
  49    IncomeTaxesSignificantComponentsofDeferredTaxAssetsandLiabi…
  27    IncomeTaxesTables
  70    InsiderTradingArrangements
  71    InsiderTradingPoliciesProc
  15    Leases
  51    LeasesAdditionalInformationDetails
  53    LeasesLeaseLiabilityMaturitiesDetails
  52    LeasesROUAssetsandLeaseLiabilitiesDetails
  28    LeasesTables
  12    PropertyPlantandEquipment
  43    PropertyPlantandEquipmentAdditionalInformationDetails
  42    PropertyPlantandEquipmentGrossPropertyPlantandEquipmentbyMa…
  25    PropertyPlantandEquipmentTables
  9     Revenue
  35    RevenueAdditionalInformationDetails
  36    RevenueDeferredRevenueExpectedTimingofRealizationDetails
  34    RevenueDisaggregatedNetSalesandPortionofNetSalesThatWasPrev…
  22    RevenueTables
  18    ShareBasedCompensation
  60    ShareBasedCompensationAdditionalInformationDetails
  61    ShareBasedCompensationRestrictedStockUnitActivityandRelated…
  62    ShareBasedCompensationSummaryofShareBasedCompensationExpens…
  31    ShareBasedCompensationTables
  17    ShareholdersEquity
  58    ShareholdersEquityAdditionalInformationDetails
  30    ShareholdersEquityTables
  5     CONSOLIDATEDBALANCESHEETSParenthetical                         BalanceSheetParenthetical   ✓

In [35]:
print([attr for attr in dir(statements) if not attr.startswith('_')])

['balance_sheet', 'cashflow_statement', 'classify_statement', 'comprehensive_income', 'cover_page', 'disclosures', 'find_statement_by_primary_concept', 'get_by_category', 'get_period_views', 'get_statements_by_category', 'income_statement', 'notes', 'schedule_of_investments', 'statement_by_type', 'statement_of_equity', 'statements', 'to_dataframe', 'xbrl']

In [36]:
stmt = statements[5]
print([attr for attr in dir(stmt) if not attr.startswith('_')])
stmt_df = stmt
stmt_df

No periods with sufficient data found for Apple Inc. BalanceSheetParenthetical, returning all candidates

['REQUIRED_CONCEPTS', 'analyze_trends', 'calculate_ratios', 'canonical_type', 'docs', 'get_raw_data', 'is_segmented', 'primary_concept', 'render', 'role_or_type', 'to_dataframe', 'xbrl']

                             CONSOLIDATEDBALANCESHEETSParenthetical
                                           Year Ended

                                                     Sep 27, 2025   Sep 28, 2024   Sep 30, 2023
 ───────────────────────────────────────────────────────────────────────────────────────────────
    Common stock, par value (in dollars per share)
    Common stock, shares authorized (in shares)
    Common Stock Shares Issued
    Common Stock Shares Outstanding:

              Apple Inc. • Period ending 2025-09-27 • Fiscal FY • Source: SEC XBRL